site_name: MSc CSE Admission Prep

theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

extra_css:
  - stylesheets/extra.css